#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jorge Luis Graza Melgarejo

# Short bio or description (displayed in the header)
description: Geek | Bussines Intelligence | Web Developer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://scontent.flim12-1.fna.fbcdn.net/v/t1.6435-9/181086797_3864479496921321_8605912737412970832_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=09cbfe&_nc_eui2=AeFbbz4SSsVBgXjgJEt8CYhaJC8LBQQdJREkLwsFBB0lERBCjmp_ta0f4ySPod0U5pWK9ModkDqh-j0sUvj5SWT_&_nc_ohc=O-U_Yog87swAX88P3gR&_nc_ht=scontent.flim12-1.fna&oh=f60f6f5fdacba7006a94b3f66eaf6192&oe=60B51AD5

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: "jg.melg@gmail.com"
  facebook: "GekneS"
  flickr:
  github: "geknes"
  instagram: "jorgegrazam"
  linkedin:
  pinterest: 
  rss: # just type anything here for a working RSS icon
  twitter: "jorgegrazam"
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: "geknes"
  googleplus: # anything in your profile username that comes after plus.google.com/
  blog: "www.jorgegraza.com"


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: "geknes"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: "UA-105771010-1"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://geknes.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

fb_comment_id: 284412583282532

#comments:
#provider : "facebook"
#facebook:
#appid : 284412583282532
#num_posts : # 5 (default)
#colorscheme : # "light" (default), "dark"
